# Generated by Django 2.2.4 on 2019-10-11 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0003_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='galary',
        ),
    ]
