# Generated by Django 2.2.4 on 2019-10-11 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0005_auto_20191011_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='announcement',
            new_name='msg',
        ),
    ]
