# Generated by Django 2.2.4 on 2019-10-11 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0007_auto_20191011_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='thought',
            new_name='though',
        ),
    ]
