# Generated by Django 2.2.4 on 2019-10-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0008_auto_20191011_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thought',
            old_name='though',
            new_name='msg',
        ),
    ]
