# Generated by Django 2.2.7 on 2019-11-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0009_auto_20191011_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='achiver',
            new_name='achiever',
        ),
    ]
