# Generated by Django 3.0.3 on 2020-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_web', '0010_auto_20191111_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.TextField(default='#'),
        ),
    ]
